"""
BMKG Strong Motion Analyzer (BSMA)

Domain Types
============

Processing cache shared across the BSMA processing pipeline.

The ProcessingCache stores expensive numerical products generated by
processing plugins. Downstream plugins reuse these cached quantities
instead of recomputing them.

Design Goals
------------
- Pure domain layer
- Type-safe
- No ObsPy dependency
- Extensible
- Numerical products only
- Immutable ProcessingContext compatible
"""

from __future__ import annotations

from dataclasses import dataclass

import numpy as np
from numpy.typing import NDArray

__all__ = [
    "ProcessingCache",
]

FloatArray = NDArray[np.float64]


@dataclass(slots=True)
class ProcessingCache:
    """
    Numerical cache shared by the BSMA processing pipeline.

    Every attribute is optional.

    A value of None indicates that the corresponding quantity
    has not yet been computed.

    Notes
    -----
    This class intentionally stores only numerical products.
    Metadata, provenance, QC and processing state belong to
    their dedicated domain models.
    """

    # ==========================================================
    # Time Domain
    # ==========================================================

    velocity: FloatArray | None = None
    displacement: FloatArray | None = None
    husid_curve: FloatArray | None = None

    # ==========================================================
    # Strong Motion Parameters
    # ==========================================================

    pga: float | None = None
    pgv: float | None = None
    pgd: float | None = None

    arias_intensity: float | None = None
    cumulative_absolute_velocity: float | None = None
    significant_duration_5_75: float | None = None
    significant_duration_5_95: float | None = None

    # ==========================================================
    # Waveform Statistics
    # ==========================================================

    mean: float | None = None
    standard_deviation: float | None = None
    root_mean_square: float | None = None
    energy: float | None = None

    # ==========================================================
    # Frequency Domain
    # ==========================================================

    fft_frequency: FloatArray | None = None
    fft_amplitude: FloatArray | None = None
    fft_phase: FloatArray | None = None
    fourier_amplitude_spectrum: FloatArray | None = None
    power_spectral_density: FloatArray | None = None

    # ==========================================================
    # Response Spectrum
    # ==========================================================

    response_periods: FloatArray | None = None
    spectral_displacement: FloatArray | None = None
    spectral_velocity: FloatArray | None = None
    spectral_acceleration: FloatArray | None = None
    pseudo_spectral_velocity: FloatArray | None = None
    pseudo_spectral_acceleration: FloatArray | None = None
    peak_absolute_velocity: FloatArray | None = None

    # ==========================================================
    # Future Extensions
    # ==========================================================

    hvsr: FloatArray | None = None
    rotd50: FloatArray | None = None
    rotd100: FloatArray | None = None

    # ==========================================================
    # Helper Properties
    # ==========================================================

    @property
    def has_velocity(self) -> bool:
        """True apabila velocity telah tersedia."""
        return self.velocity is not None

    @property
    def has_displacement(self) -> bool:
        """True apabila displacement telah tersedia."""
        return self.displacement is not None

    @property
    def has_time_domain(self) -> bool:
        """True apabila seluruh hasil utama domain waktu telah tersedia."""
        return (
            self.velocity is not None
            and self.displacement is not None
        )

    @property
    def has_husid(self) -> bool:
        """True apabila Husid Curve telah dihitung."""
        return self.husid_curve is not None

    @property
    def has_waveform_statistics(self) -> bool:
        """True apabila statistik dasar waveform telah dihitung."""
        return all(
            value is not None
            for value in (
                self.mean,
                self.standard_deviation,
                self.root_mean_square,
                self.energy,
            )
        )

    @property
    def has_strong_motion_parameters(self) -> bool:
        """True apabila parameter Strong Motion utama telah tersedia."""
        return all(
            value is not None
            for value in (
                self.pga,
                self.pgv,
                self.pgd,
                self.arias_intensity,
                self.cumulative_absolute_velocity,
                self.significant_duration_5_75,
                self.significant_duration_5_95,
            )
        )

    @property
    def has_fft(self) -> bool:
        """True apabila FFT telah dihitung."""
        return (
            self.fft_frequency is not None
            and self.fft_amplitude is not None
        )

    @property
    def has_frequency_domain(self) -> bool:
        """Alias untuk has_fft. Memudahkan pembacaan pipeline dan GUI."""
        return self.has_fft

    @property
    def has_response_spectrum(self) -> bool:
        """
        True apabila trinitas Response Spectrum (SD, PSV, PSA) telah tersedia.
        Mencegah downstream plugin membaca spektrum parsial.
        """
        return all(
            value is not None
            for value in (
                self.response_periods,
                self.spectral_displacement,
                self.pseudo_spectral_velocity,
                self.pseudo_spectral_acceleration,
            )
        )

    @property
    def is_empty(self) -> bool:
        """True apabila seluruh cache masih kosong."""
        return all(
            getattr(self, field_name) is None
            for field_name in self.__dataclass_fields__
        )

    # ==========================================================
    # Utilities (Cascading Invalidation Enforced)
    # ==========================================================

    def clear(self) -> None:
        """
        Clear the entire numerical cache.

        This method is called whenever the waveform has been
        modified (baseline correction, detrending, filtering,
        tapering, etc.), since every derived quantity becomes
        invalid and must be recomputed.
        """
        for field_name in self.__dataclass_fields__:
            setattr(self, field_name, None)

    def clear_time_domain(self) -> None:
        """
        Clear all quantities derived from the time domain.

        If time domain components (velocity, displacement) are cleared, 
        all downstream frequency and spectral products MUST also be cleared 
        to prevent stale data propagation (Cascading Invalidation).
        """
        # Time-domain signals
        self.velocity = None
        self.displacement = None
        self.husid_curve = None

        # Strong Motion Parameters
        self.pga = None
        self.pgv = None
        self.pgd = None
        self.arias_intensity = None
        self.cumulative_absolute_velocity = None
        self.significant_duration_5_75 = None
        self.significant_duration_5_95 = None

        # Statistics
        self.mean = None
        self.standard_deviation = None
        self.root_mean_square = None
        self.energy = None

        # Enforce cascading invalidation
        self.clear_frequency_domain()
        self.clear_response_spectrum()

    def clear_frequency_domain(self) -> None:
        """Clear all frequency-domain products."""
        self.fft_frequency = None
        self.fft_amplitude = None
        self.fft_phase = None
        self.fourier_amplitude_spectrum = None
        self.power_spectral_density = None
        self.hvsr = None

    def clear_response_spectrum(self) -> None:
        """Clear all response spectrum products."""
        self.response_periods = None
        self.spectral_displacement = None
        self.spectral_velocity = None
        self.spectral_acceleration = None
        self.pseudo_spectral_velocity = None
        self.pseudo_spectral_acceleration = None
        self.peak_absolute_velocity = None
        self.rotd50 = None
        self.rotd100 = None

    # ==========================================================
    # Serialization
    # ==========================================================

    def to_dict(self) -> dict[str, bool]:
        """
        Return a lightweight cache summary.

        Numerical arrays are intentionally omitted so this
        representation remains inexpensive for logging,
        diagnostics and JSON serialization.
        """
        return {
            "empty": self.is_empty,
            "time_domain": self.has_time_domain,
            "waveform_statistics": self.has_waveform_statistics,
            "strong_motion": self.has_strong_motion_parameters,
            "frequency_domain": self.has_frequency_domain,
            "response_spectrum": self.has_response_spectrum,
            "husid_curve": self.has_husid,
            "hvsr": self.hvsr is not None,
            "rotd50": self.rotd50 is not None,
            "rotd100": self.rotd100 is not None,
        }

    # ==========================================================
    # Representation
    # ==========================================================

    def __repr__(self) -> str:
        return (
            f"{self.__class__.__name__}("
            f"time_domain={self.has_time_domain}, "
            f"strong_motion={self.has_strong_motion_parameters}, "
            f"frequency_domain={self.has_frequency_domain}, "
            f"response_spectrum={self.has_response_spectrum})"
        )