"""
BMKG Strong Motion Analyzer (BSMA)

Domain Types
============

Quality Control domain models.

This module defines immutable QC objects shared across the entire
processing pipeline.

Design goals
------------
- Pure domain layer (no dependency on ObsPy or NumPy)
- Strong typing
- Immutable QCResult
- Automatic overall QC evaluation
- JSON-friendly serialization
"""

from __future__ import annotations

from dataclasses import dataclass, field
from enum import Enum
from types import MappingProxyType
from typing import Any, Mapping


__all__ = [
    "QCStatus",
    "QCSeverity",
    "QCResult",
    "QCReport",
]


# ----------------------------------------------------------------------
# ENUMS
# ----------------------------------------------------------------------


class QCStatus(str, Enum):
    """
    Overall validation status.
    """

    PASS = "PASS"
    WARNING = "WARNING"
    FAIL = "FAIL"


class QCSeverity(str, Enum):
    """
    Severity level of QC findings.
    """

    LOW = "LOW"
    MEDIUM = "MEDIUM"
    HIGH = "HIGH"
    CRITICAL = "CRITICAL"


# ----------------------------------------------------------------------
# QC RESULT
# ----------------------------------------------------------------------


@dataclass(slots=True, frozen=True)
class QCResult:
    """
    Result returned by a single validator.

    Parameters
    ----------
    status
        PASS / WARNING / FAIL.
    severity
        Severity of the finding.
    validator_name
        Name of validator.
    message
        Human-readable explanation.
    metrics
        Immutable numerical metrics generated by validator.
    """

    status: QCStatus
    severity: QCSeverity
    validator_name: str
    message: str
    metrics: Mapping[str, Any] = field(default_factory=dict)

    def __post_init__(self) -> None:
        object.__setattr__(
            self,
            "metrics",
            MappingProxyType(dict(self.metrics)),
        )

    def to_dict(self) -> dict[str, Any]:
        return {
            "status": self.status.value,
            "severity": self.severity.value,
            "validator_name": self.validator_name,
            "message": self.message,
            "metrics": dict(self.metrics),
        }


# ----------------------------------------------------------------------
# QC REPORT
# ----------------------------------------------------------------------


@dataclass(slots=True)
class QCReport:
    """
    Collection of QC results produced during processing.

    Notes
    -----
    Overall status is computed dynamically.

    Rules

    FAIL     -> if at least one validator fails

    WARNING  -> if no FAIL exists but at least one WARNING exists

    PASS     -> otherwise
    """

    results: dict[str, QCResult] = field(default_factory=dict)

    # ------------------------------------------------------------------

    @property
    def overall_status(self) -> QCStatus:

        if any(r.status is QCStatus.FAIL for r in self.results.values()):
            return QCStatus.FAIL

        if any(r.status is QCStatus.WARNING for r in self.results.values()):
            return QCStatus.WARNING

        return QCStatus.PASS

    # ------------------------------------------------------------------

    def add_result(self, result: QCResult) -> None:
        """
        Add or replace a validator result.
        """
        self.results[result.validator_name] = result

    # ------------------------------------------------------------------

    def get(self, validator_name: str) -> QCResult | None:
        """
        Retrieve validator result.
        """
        return self.results.get(validator_name)

    # ------------------------------------------------------------------

    def passed(self) -> dict[str, QCResult]:
        """
        Return all PASS validators.
        """
        return {
            k: v
            for k, v in self.results.items()
            if v.status is QCStatus.PASS
        }

    # ------------------------------------------------------------------

    def warnings(self) -> dict[str, QCResult]:
        """
        Return WARNING validators.
        """
        return {
            k: v
            for k, v in self.results.items()
            if v.status is QCStatus.WARNING
        }

    # ------------------------------------------------------------------

    def failed(self) -> dict[str, QCResult]:
        """
        Return FAIL validators.
        """
        return {
            k: v
            for k, v in self.results.items()
            if v.status is QCStatus.FAIL
        }

    # ------------------------------------------------------------------

    def summary(self) -> str:
        """
        Human-readable QC summary.
        """

        passed = len(self.passed())
        warning = len(self.warnings())
        failed = len(self.failed())

        return (
            f"PASS={passed} | "
            f"WARNING={warning} | "
            f"FAIL={failed}"
        )

    # ------------------------------------------------------------------

    def to_dict(self) -> dict[str, Any]:
        """
        Serialize report.
        """

        return {
            "overall_status": self.overall_status.value,
            "results": {
                name: result.to_dict()
                for name, result in self.results.items()
            },
        }

    # ------------------------------------------------------------------

    def __len__(self) -> int:
        return len(self.results)

    def __contains__(self, validator_name: str) -> bool:
        return validator_name in self.results

    def __iter__(self):
        return iter(self.results.values())