"""
BMKG Strong Motion Analyzer (BSMA)

Module: core/types/qc.py

Description
-----------
Domain models for Quality Control (QC).

This module contains the immutable domain representation of QC
findings and the mutable aggregate report used by the processing
pipeline.

Design Principles
-----------------
- Pure domain layer
- No ObsPy dependency
- No NumPy dependency
- Strong typing
- Immutable QCResult
- Explicit QC aggregation
- JSON-friendly serialization
- Suitable for batch processing
- Station-independent
"""

from __future__ import annotations

from dataclasses import dataclass, field
from enum import Enum
from types import MappingProxyType
from typing import Any, Iterator, Mapping

__all__ = [
    "QCStatus",
    "QCSeverity",
    "QCResult",
    "QCReport",
]


# ============================================================================
# ENUMS
# ============================================================================


class QCStatus(str, Enum):
    """
    Overall validation status of a QC validator.

    PASS
        No abnormality was identified by the validator.

    WARNING
        An anomaly was identified, but the waveform may still be
        scientifically usable depending on the analysis objective.

    FAIL
        The validator identified a condition that makes the affected
        waveform or processing result unsuitable for reliable analysis.
    """

    PASS = "PASS"
    WARNING = "WARNING"
    FAIL = "FAIL"


class QCSeverity(str, Enum):
    """
    Severity classification of a QC finding.

    LOW
        Minor anomaly with negligible expected impact.

    MEDIUM
        Anomaly that may affect some downstream analyses.

    HIGH
        Significant anomaly requiring caution or additional processing.

    CRITICAL
        Severe data integrity problem that can invalidate the waveform.
    """

    LOW = "LOW"
    MEDIUM = "MEDIUM"
    HIGH = "HIGH"
    CRITICAL = "CRITICAL"


# ============================================================================
# QC RESULT
# ============================================================================


@dataclass(slots=True, frozen=True)
class QCResult:
    """
    Immutable result produced by one QC validator.

    Parameters
    ----------
    status
        Validation result: PASS, WARNING, or FAIL.

    severity
        Scientific/operational severity of the finding.

    validator_name
        Unique identifier of the validator.

    message
        Human-readable description of the QC finding.

    metrics
        Numerical or structured diagnostic values generated by the
        validator.

    Notes
    -----
    ``metrics`` is converted into ``MappingProxyType`` so callers cannot
    mutate the result after construction.

    The class intentionally contains no waveform data. Numerical
    waveform processing remains the responsibility of the processing
    layer.
    """

    status: QCStatus
    severity: QCSeverity
    validator_name: str
    message: str
    metrics: Mapping[str, Any] = field(default_factory=dict)

    def __post_init__(self) -> None:
        """
        Validate and freeze the QC result.
        """
        if not self.validator_name.strip():
            raise ValueError("validator_name must not be empty.")

        if not self.message.strip():
            raise ValueError("message must not be empty.")

        if not isinstance(self.status, QCStatus):
            raise TypeError(
                "status must be an instance of QCStatus."
            )

        if not isinstance(self.severity, QCSeverity):
            raise TypeError(
                "severity must be an instance of QCSeverity."
            )

        object.__setattr__(
            self,
            "metrics",
            MappingProxyType(dict(self.metrics)),
        )

    @property
    def is_pass(self) -> bool:
        """Return True when the validator passed."""
        return self.status is QCStatus.PASS

    @property
    def is_warning(self) -> bool:
        """Return True when the validator produced a warning."""
        return self.status is QCStatus.WARNING

    @property
    def is_fail(self) -> bool:
        """Return True when the validator failed."""
        return self.status is QCStatus.FAIL

    @property
    def is_critical(self) -> bool:
        """Return True when the finding has critical severity."""
        return self.severity is QCSeverity.CRITICAL

    def to_dict(self) -> dict[str, Any]:
        """
        Serialize the QC result into a JSON-compatible dictionary.

        Notes
        -----
        Values contained inside ``metrics`` are expected to be
        serialization-safe. Conversion of NumPy scalar/array objects,
        if any, belongs to the processing or serialization layer rather
        than this pure domain model.
        """
        return {
            "status": self.status.value,
            "severity": self.severity.value,
            "validator_name": self.validator_name,
            "message": self.message,
            "metrics": dict(self.metrics),
        }


# ============================================================================
# QC REPORT
# ============================================================================


@dataclass(slots=True)
class QCReport:
    """
    Aggregate QC report for a waveform or processing operation.

    Results are indexed by ``validator_name``.

    Overall status follows deterministic precedence:

        FAIL > WARNING > PASS

    Therefore:

    - Any FAIL result makes the report FAIL.
    - If there is no FAIL but at least one WARNING, the report is WARNING.
    - If all validators PASS, the report is PASS.
    - If no validator has been executed, the report returns PASS.

    Notes
    -----
    The report itself is intentionally mutable because QC validators
    normally execute sequentially and append results during a pipeline
    run.

    The individual ``QCResult`` objects remain immutable.
    """

    results: dict[str, QCResult] = field(default_factory=dict)

    # ------------------------------------------------------------------
    # Overall State
    # ------------------------------------------------------------------

    @property
    def overall_status(self) -> QCStatus:
        """
        Calculate the overall QC status.

        Status precedence:

            FAIL > WARNING > PASS
        """
        if any(
            result.status is QCStatus.FAIL
            for result in self.results.values()
        ):
            return QCStatus.FAIL

        if any(
            result.status is QCStatus.WARNING
            for result in self.results.values()
        ):
            return QCStatus.WARNING

        return QCStatus.PASS

    @property
    def overall_severity(self) -> QCSeverity:
        """
        Return the highest severity present in the report.

        Severity precedence:

            CRITICAL > HIGH > MEDIUM > LOW

        An empty report has LOW severity because no abnormality has
        been identified.
        """
        severity_rank = {
            QCSeverity.LOW: 0,
            QCSeverity.MEDIUM: 1,
            QCSeverity.HIGH: 2,
            QCSeverity.CRITICAL: 3,
        }

        if not self.results:
            return QCSeverity.LOW

        return max(
            (result.severity for result in self.results.values()),
            key=severity_rank.__getitem__,
        )

    # ------------------------------------------------------------------
    # Convenience Flags
    # ------------------------------------------------------------------

    @property
    def is_passed(self) -> bool:
        """Return True when the complete QC report passes."""
        return self.overall_status is QCStatus.PASS

    @property
    def has_warnings(self) -> bool:
        """Return True when at least one warning exists."""
        return self.overall_status is QCStatus.WARNING

    @property
    def has_failures(self) -> bool:
        """Return True when at least one failure exists."""
        return self.overall_status is QCStatus.FAIL

    @property
    def has_critical_issue(self) -> bool:
        """Return True when at least one critical finding exists."""
        return any(
            result.severity is QCSeverity.CRITICAL
            for result in self.results.values()
        )

    # ------------------------------------------------------------------
    # Result Management
    # ------------------------------------------------------------------

    def add_result(self, result: QCResult) -> None:
        """
        Add or replace a validator result.

        Parameters
        ----------
        result
            Immutable QCResult generated by a validator.
        """
        if not isinstance(result, QCResult):
            raise TypeError(
                "result must be an instance of QCResult."
            )

        self.results[result.validator_name] = result

    def remove_result(self, validator_name: str) -> QCResult | None:
        """
        Remove and return a validator result.

        Returns
        -------
        QCResult or None
            Removed result, or None if the validator does not exist.
        """
        return self.results.pop(validator_name, None)

    def get(self, validator_name: str) -> QCResult | None:
        """
        Retrieve a validator result by name.
        """
        return self.results.get(validator_name)

    # ------------------------------------------------------------------
    # Result Groups
    # ------------------------------------------------------------------

    def passed(self) -> dict[str, QCResult]:
        """Return all validators with PASS status."""
        return {
            name: result
            for name, result in self.results.items()
            if result.status is QCStatus.PASS
        }

    def warnings(self) -> dict[str, QCResult]:
        """Return all validators with WARNING status."""
        return {
            name: result
            for name, result in self.results.items()
            if result.status is QCStatus.WARNING
        }

    def failed(self) -> dict[str, QCResult]:
        """Return all validators with FAIL status."""
        return {
            name: result
            for name, result in self.results.items()
            if result.status is QCStatus.FAIL
        }

    def critical(self) -> dict[str, QCResult]:
        """Return all validators with CRITICAL severity."""
        return {
            name: result
            for name, result in self.results.items()
            if result.severity is QCSeverity.CRITICAL
        }

    # ------------------------------------------------------------------
    # Statistics
    # ------------------------------------------------------------------

    @property
    def pass_count(self) -> int:
        """Number of PASS validators."""
        return sum(
            result.status is QCStatus.PASS
            for result in self.results.values()
        )

    @property
    def warning_count(self) -> int:
        """Number of WARNING validators."""
        return sum(
            result.status is QCStatus.WARNING
            for result in self.results.values()
        )

    @property
    def fail_count(self) -> int:
        """Number of FAIL validators."""
        return sum(
            result.status is QCStatus.FAIL
            for result in self.results.values()
        )

    @property
    def critical_count(self) -> int:
        """Number of CRITICAL findings."""
        return sum(
            result.severity is QCSeverity.CRITICAL
            for result in self.results.values()
        )

    # ------------------------------------------------------------------
    # Summary
    # ------------------------------------------------------------------

    def summary(self) -> str:
        """
        Return a concise human-readable QC summary.
        """
        return (
            f"STATUS={self.overall_status.value} | "
            f"SEVERITY={self.overall_severity.value} | "
            f"PASS={self.pass_count} | "
            f"WARNING={self.warning_count} | "
            f"FAIL={self.fail_count}"
        )

    # ------------------------------------------------------------------
    # Serialization
    # ------------------------------------------------------------------

    def to_dict(self) -> dict[str, Any]:
        """
        Serialize the complete QC report.
        """
        return {
            "overall_status": self.overall_status.value,
            "overall_severity": self.overall_severity.value,
            "is_passed": self.is_passed,
            "has_warnings": self.has_warnings,
            "has_failures": self.has_failures,
            "has_critical_issue": self.has_critical_issue,
            "pass_count": self.pass_count,
            "warning_count": self.warning_count,
            "fail_count": self.fail_count,
            "critical_count": self.critical_count,
            "results": {
                name: result.to_dict()
                for name, result in self.results.items()
            },
        }

    # ------------------------------------------------------------------
    # Collection Protocol
    # ------------------------------------------------------------------

    def __len__(self) -> int:
        """Return the number of validators executed."""
        return len(self.results)

    def __contains__(self, validator_name: str) -> bool:
        """Return True when a validator result exists."""
        return validator_name in self.results

    def __iter__(self) -> Iterator[QCResult]:
        """Iterate over QC results."""
        return iter(self.results.values())

    # ------------------------------------------------------------------
    # Representation
    # ------------------------------------------------------------------

    def __repr__(self) -> str:
        return (
            f"{self.__class__.__name__}("
            f"status={self.overall_status.value!r}, "
            f"severity={self.overall_severity.value!r}, "
            f"results={len(self.results)})"
        )